version: '3'

services:
  traccar:
    image: traccar/traccar
    container_name: traccar
    restart: unless-stopped
    ports:
      - 8082:8082
      - 5000-5150:5000-5150
    volumes:
      - ./data:/opt/traccar/data
      - ./conf:/opt/traccar/conf